"""add is_active to students

Revision ID: 7fc957b662e8
Revises: 8f0ad9892eed
Create Date: 2026-07-09 09:51:54.260107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc957b662e8'
down_revision: Union[str, Sequence[str], None] = '8f0ad9892eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.alter_column('courses', 'course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('departments', 'department_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('instructors', 'instructor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('students', 'student_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'students', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'student_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('students', 'is_active')
    op.alter_column('instructors', 'instructor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('departments', 'department_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('courses', 'course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('course_schedules')
    # ### end Alembic commands ###
